# Generated by Django 3.2.10 on 2022-01-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField()),
                ('dob', models.DateField()),
                ('specie', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('is_extinct', models.BooleanField()),
                ('pic_url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
