# Generated by Django 4.0.1 on 2022-01-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='viewing_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='specie',
            field=models.CharField(choices=[('mammal', 'Mammal'), ('amphibian', 'Amphibian'), ('reptile', 'Reptile'), ('pices', 'Pices'), ('aves', 'Aves')], max_length=200),
        ),
    ]
