# Generated by Django 4.0.1 on 2022-01-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_animal_viewing_price_alter_animal_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='viewing_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
