# Generated by Django 3.2.10 on 2022-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
